spring:
  application.name: api-gateway
  kafka:
    consumer:
      group-id: api-gateway
    producer:
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
