server:
  port: 8082
spring:
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            value:
              default:
                type: java.lang.String
        state.dir: ./kafka-streams
    consumer:
      group-id: game-data

  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:9092,localhost:9093
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
                deserialization.exception.handler: by.bsuir.seabattle.exception.DeserializationExceptionHandlerImpl
              specific.avro.reader: true
              schema.registry.url: http://localhost:8081
              dynamicSchemaGenerationEnabled: false
      bindings:
        processGameCreationRequests-in-0:
          destination: games-events
          group: game-creation-request-processor
        processGameCreationRequests-out-0:
          destination: games-topic
        processViewRequests-in-0:
          destination: games-events
          group: view-request-processor-0
        processViewRequests-out-0:
          destination: user-notifications
      instance-count: 2
      instance-index: 0

    function:
      definition: processGameCreationRequests;processViewRequests;
  main:
    allow-bean-definition-overriding: true