server:
  port: 8081

spring:
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            value:
              default:
                type: java.lang.String
    consumer:
      group-id: game-data


  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.springframework.kafka.support.serializer.JsonSerde
      bindings:
        processGameCreationRequests-in-0:
          destination: game-creation-requests
        processGameCreationRequests-out-0:
          destination: games-topic

    function:
      definition: processGameCreationRequests;