spring:
  kafka:
    streams:
      bootstrap-servers: localhost:9092
      properties:
        state.dir: ./kafka-streams
    consumer:
      group-id: user-notifications

  cloud:
    stream:
      kafka:
        streams:
          binder:
            brokers: localhost:9092
            configuration:
              default:
                key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value.serde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
              specific.avro.reader: true
              schema.registry.url: http://localhost:8081
              dynamicSchemaGenerationEnabled: false
            functions:
              processGameEvents:
                applicationId: game-events-processors
      bindings:
        processGameEvents-in-0:
          destination: game-events
        processGameEvents-out-0:
          destination: player-events
      instance-count: 2
      instance-index: 0

    function:
      definition: processGameEvents;
logging:
  level:
    by.bsuir.seabattle.*: INFO